# Generated by Django 4.0.6 on 2022-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Message', models.TextField()),
            ],
        ),
    ]
