# Generated by Django 4.0.6 on 2022-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=50)),
                ('Website_Link', models.TextField()),
            ],
        ),
    ]
