# Generated by Django 4.0.6 on 2022-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='metropolitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=50)),
                ('Website_Link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=50)),
                ('Website_Link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rural_municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=50)),
                ('Website_Link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sub_metropolitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(max_length=50)),
                ('Website_Link', models.TextField()),
            ],
        ),
    ]
