# Generated by Django 4.0.6 on 2022-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_metropolitan_municipality_rural_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metropolitan',
            name='Website_Link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='Website_Link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='Website_Link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rural_municipality',
            name='Website_Link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_metropolitan',
            name='Website_Link',
            field=models.CharField(max_length=100),
        ),
    ]
